### ISSUE TITLE
Keyboard not showing up on android although Input field is focussed.

### ISSUE THREAD

**Issue by gauravsaluja2006** [Twotalltotems/react-native-otp-input#1]
This was working fine on iOS although. 
After clicking on the OTP field, the field had blue/green border around it to show that it was active but the keyboard didn't show up.

I had to replace the _focusField function  to make it work on android.

`
_focusField = index => {
    this.fields[index].blur();

    setTimeout(() => {
      this.fields[index].focus();
    }, 100);

    this.setState({
      selectedIndex: index
    });
};
`

Also, textContentType= oneTimeCode is only for iOS 12+ and causes warning in other devices.

**Comment by gauravsaluja2006** [comment]
This caused the keyboard to reappear after it blurs when the last field is filled. Also, had to change

`_blurAllFields = () => {
    for (field of this.fields) {
      setTimeout(() => {
        field.blur();
      }, 100);
    }
    this.setState({
      selectedIndex: -1
    });
  };`

**Comment by ansonyao** [comment]
Thanks for the feedback @gauravsaluja2006. I will look into these issues. PRs are welcome too, if you would like to.

**Comment by ansonyao** [comment]
Hey @gauravsaluja2006, I tried to run the sample project on a couple of Android phones, including Samsung S6 real device, Nexus 5x Android Studio simulator, Samsung S7 Genymotion simulator. But I cannot reproduce your issue. The keyboard shows up every time I enter the page and it does show up again when I press on the input. Could you please try to run the example project on your device and to see if it works? 

For the iOS warning, I have published a new version  v1.0.16. It should be fixed now.

**Comment by gauravsaluja2006** [comment]
Thanks for looking into it. I will try if i can replicate it on a new project. Will add proper details in that case.

**Comment by ansonyao** [comment]
Now we realized this issue is actually caused by the android back button. You can check discussion in Issue #3. We have fixed this problem in v1.0.22.

**Comment by Muheet707** [comment]
Fixed my issue by just one line code.
autoFocusOnLoad={false}
