### ISSUE TITLE
Create security text entry prop to hide input contents

### ISSUE THREAD

**Issue by sumitagrawal** [Twotalltotems/react-native-otp-input#10]
Hi 
,i need to use it as for Password field how  can I change it

**Comment by ansonyao** [comment]
Hi, sumitagrawal, we have not implemented a property to hide the one time passcode. But you can achieve what you want to do by using this library as a controlled component. Basically you have to manage the state in your component and provide the value (like `****`) to `code` property and also provide the onCodeChange handler. You can take a look at the commented out lines in the example, especially the following two lines

// code={this.state.code} //You can supply this prop or not. The component will be used as a controlled / uncontrolled component respectively.
    // onCodeChanged = {code => { this.setState({code})}}

**Comment by vishal767** [comment]
Can we add a `secureTextEntry` prop ?

**Comment by ansonyao** [comment]
hmm. Yeah, I guess that makes sense

**Comment by fpena** [comment]
This was added! ⭐️
