### ISSUE TITLE
Input fields won't update when passing new code

### ISSUE THREAD

**Issue by tuanna1601** [Twotalltotems/react-native-otp-input#11]
**Describe the bug**
When I update the value in my component and pass the new value through `code` props, the inputs still show the previous values. (To clear the values when the inputed OTP is incorrect)

**To Reproduce**
1. Create a component with a code state
2. Pass code state to OTPInputView code prop
3. Update code state in created component
4. The inputs still shows the old values

**Expected behavior**
The inputs should update their values when code prop is updated

**Comment by DY205** [comment]
same issue

**Comment by noumantahir** [comment]
same issue here

**Comment by fpena** [comment]
This should be fixed ⭐️
