### ISSUE TITLE
Keyboard layout problem

### ISSUE THREAD

**Issue by Ritesh3011** [Twotalltotems/react-native-otp-input#3]
I have use this OTP screen.
When the screen load then the keyboard for OTP is showing.
then , if you press back button, then key board will hidden.. and not open again..
please fix this.

**Comment by ansonyao** [comment]
Thanks for reporting the issue! Does it happen on all android device or a specific model?

**Comment by Ritesh3011** [comment]
In my Redmi 6 pro,Moto z3 play, Asus max pro 1.
this is my devices.. i dont know on others

**Comment by ansonyao** [comment]
Oh no, that is quite a long list... So it probably has problem with lots of Android devices. Thanks Ritesh!  Will look into it.

**Comment by joegichuru** [comment]
any status on this? am experiencing the same on both huawei y5 and nokia 3.1.

**Comment by ansonyao** [comment]
Not yet. Have been a busy week for me. Will work on this issue soon.

**Comment by ansonyao** [comment]
This is because of a bug in React Native 
[Issue 19366](https://github.com/facebook/react-native/issues/19366)
To fix this issue, we have added a listener for the Keyboard dismiss event in the latest version 1.0.22. Please upgrade to this new version, it should work properly now after user pressing the back button.

**Comment by tuvudu** [comment]
> This is because of a bug in React Native [Issue 19366](https://github.com/facebook/react-native/issues/19366)
> To fix this issue, we have added a listener for the Keyboard dismiss event in the latest version 1.0.22. Please upgrade to this new version, it should work properly now after user pressing the back button.

may you recheck this issue, I can't show keyboard with autoFocusLoad = true (first rendered)
it worked with https://github.com/facebook/react-native/issues/19366#issuecomment-390956574
