### ISSUE TITLE
More than "pinCount" code can be entered

### ISSUE THREAD

**Issue by ajaykumar97** [Twotalltotems/react-native-otp-input#30]
**Describe the bug**
I have given the ``pinCount={4}`` to the ``react-native-otp-input`` component. If a user types the input slowly, then it works fine. but if the user types/enter the OTP very fast, it allows the user to enter the OTP more than the given ``pinCount``.

As I have given the ``pinCount={4}``, I am able to type more than 4 digits.

**To Reproduce**
1. Enter the OTP very fast
2. More than the given ``pinCount`` OTP digits will be returned from the ``onCodeFilled`` function

**Expected behavior**
User will not be able to enter the OTP code more than the given ``pinCount``

**Screenshots**
//debugger output with slow and fast typing
https://prnt.sc/q8sxqd

//entered code
https://prnt.sc/q8sxeq

**Smartphone (please complete the following information):**
 - Device: Google Pixel 2
 - OS: Android Oreo
 - react-native-otp-input: 1.1.2

**Comment by whimsicaldreamer** [comment]
I am encountering this issue too. In my case, if a user tries to edit a entered value, the new value gets added at the end in the state.

**Comment by BeckyWu220** [comment]
Fixes had been merged in to master branch and will be included in the next release. Close the issue now.

**Comment by mujuappsile** [comment]
I have face same issues @BeckyWu220

**Comment by icc-guerrero** [comment]
Same here
