### ISSUE TITLE
Store code value to state

### ISSUE THREAD

**Issue by AkashThoriya** [Twotalltotems/react-native-otp-input#4]
I want to store code value to the state;
then I will set that state to a variable which will be used for authentication. 
[i want to use that code authenticate user]

please help me

**Comment by fpena** [comment]
Hi @AkashThoriya. 

Are you talking about a state variable for a particular component? 
Can you maybe share some code to give more context?

Thanks!

**Comment by ansonyao** [comment]
Hey @AkashThoriya 

I guess you just need to do this in the callback:

```
onCodeFilled = {(code => {
             this.setState({ code })
          })}
```
Then the code will be in your state.
