### ISSUE TITLE
Pin Number not coming in from SMS

### ISSUE THREAD

**Issue by codeundercoverdev** [Twotalltotems/react-native-otp-input#42]
I have the following code:

    <OTPInputView
        style={{width: '100%', height: 200}}
        pinCount={4}
        code={this.state.pinNumber} //You can supply this prop or not. The component will be used as a controlled / uncontrolled component respectively.
        onCodeChanged = {pinNumber => { this.setState({pinNumber})}}
        autoFocusOnLoad
        codeInputFieldStyle={styles.underlineStyleBase}
        codeInputHighlightStyle={styles.underlineStyleHighLighted}
        onCodeFilled = {(pinNumber => {
            console.log(`pinNumber is ${pinNumber}, you are good to go!`)
            this.submitPinNumber();
        })}
    />

The input field appears and the `onCodeFilled` works.  But, the keyboard isn't detecting the number from the text.  A user still has to type it in manually.   The message in sms is: "Hello there! Here is your pin: 8888".  How do I get the keyboard on ios to detect the message? I am using ios 13.1 and react-native 0.61.5.

**Comment by BeckyWu220** [comment]
Hi @codeundercoverdev  I believe the issue happened on your message format. Please make sure your message has the keyword 'code' or 'passcode'. For example, sending 'passcode: 888888' as message to your real device with valid phone number. 
![OTP](https://user-images.githubusercontent.com/16603120/74390269-9906cb00-4db5-11ea-8adb-f33c7a8cd3c3.jpg)
