### ISSUE TITLE
componentWillReceiveProps is deprecating

### ISSUE THREAD

**Issue by aevaldas** [Twotalltotems/react-native-otp-input#5]
**Describe the bug**
componentWillReceiveProps is deprecating.

**Screenshots**
![image](https://user-images.githubusercontent.com/38099310/61530224-2787b980-aa2c-11e9-9d44-bba32429cc66.png)

**Comment by ansonyao** [comment]
Thanks for reporting it.

Just published version 1.0.23. Should have fixed it there.
