### ISSUE TITLE
autoFocusOnLoad does not work if the keyboard was active in the previous screen

### ISSUE THREAD

**Issue by aevaldas** [Twotalltotems/react-native-otp-input#7]
**Describe the bug**
`autoFocusOnLoad` (keyboard does not appear) does not work if the keyboard was active in the previous screen.

**To Reproduce**
Required environment: two screens.
1. On the first screen create input and button to navigate to the second screen.
2. On the second screen create <OTPInputView autoFocusOnLoad></OTPInputView>

1. Click on the input, to show the keyboard.
2. Click on the button, to navigate to the second screen.

**Expected behavior**
After navigating to the second screen, the keyboard for OTPInputView should appear.

**Smartphone (please complete the following information):**
 - Device: iPhone X
 - OS: IOS 12.4

**Additional context**
If I don't have the keyboard open on the first screen, OTPInputView appears on the second screen.
It seems like `this.focusField(focusIndex)` called after some time would solve this issue.

**Comment by ansonyao** [comment]
Thanks for reporting the bug in details! Will look into it!

**Comment by ShaiMahnai** [comment]
that solution doesn't work for me. still not auto focusing
