### ISSUE TITLE
auto fill not work on android 8 (React Native 0.58)

### ISSUE THREAD

**Issue by hariantara** [Twotalltotems/react-native-otp-input#9]
The OTPInput View not auto fill the input when SMS receive or new come.
Request SMS OTP Code from sendgrid, and receive SMS from sendgrid, but the input not autofill the form
It should auto fill the text input when SMS received from sendgrid

Tested on device: 
 - Device: [e.g. Xiaomi Mi 8 SE]
 - OS: [e.g. Android 8]

**Comment by ansonyao** [comment]
Did you click the copy button and it does not show up or there is no copy button at all?

**Comment by hariantara** [comment]
No copy button on notification bar, so cant copy, there is any way to to autofill ? on your example what phone and what android version are uses ? because on Mi 8 SE no copy button on notification bar

**Comment by ansonyao** [comment]
You will need that copy button. Try to change the text message. You need to let the Android know that it is an OTP message. Something like Your verification code for XYZ app is 1234 might trigger the copy buttton.

**Comment by hariantara** [comment]
Okay will try to change the wording SMS first, because on Mi 9 SE there is no copy feature. Hope it will work.
Thank you for your response

**Comment by rmamtaventures** [comment]
No copy button on one plus device in notifiaction bar. what i can do for autofill?

**Comment by abbyhilman** [comment]
same issue, in android 8 auto fill not working
